pipeline {
    agent any 
    stages{
        stage('Database'){
            steps{
                pwd
                ls 
                sh './scripts/database.sh'
            }
        }
        stage('Test'){
            steps{
                sh './scripts/test.sh'
            }
        }
        stage('Build'){
            steps{
                sh './scripts/build.sh'
            }
        }
        stage('Deploy'){
            steps{
                sh './scripts/deploy.sh'
            }
        }                   
    }
}
